### ISSUE TITLE
Elogio! Funciona super bem!!!

### ISSUE THREAD

**Issue by vissoci** [InsomniumBR/EtiquetasCorreiosMagento#1]
Só pra constar, fica aqui o meu elogio. O módulo funciona perfeitamente bem!!!!
Solução simples e extremamente útil!
Parabéns @InsomniumBR  e demais que contribuíram.

**Comment by InsomniumBR** [comment]
@apzeiro agradeço, mas o trabalho todo é do Fabiano Santos, que fez o original! =]
Eu só fiz pequenas modificações.
